export const ADD_TODO_ITEM = 'ADD_TODO_ITEM';
export const REMOVE_TODO_ITEM = 'REMOVE_TODO_ITEM';
export const CHANGE_CHECK_STATUS_TODO_ITEM = 'CHANGE_CHECK_STATUS_TODO_ITEM';
export const CHANGE_TODO_ITEM_TEXT = 'CHANGE_TODO_ITEM_TEXT';
