export const ADD_TODO_ITEM = 'ADD_TODO_ITEM';
export const REMOVE_TODO_ITEM = 'REMOVE_TODO_ITEM';
export const CHECK_TODO_ITEM = 'CHECK_TODO_ITEM';
export const UNCHECK_TODO_ITEM = 'UNCHECK_TODO_ITEM';
